ALTER TABLE checkissuance
ADD COLUMN clearing_no VARCHAR(255) NOT NULL,
ADD COLUMN clearing_date DATE NOT NULL,
ADD COLUMN company VARCHAR(255) NOT NULL,
ADD COLUMN total_gross DECIMAL(10, 2) NOT NULL;
